# This workflow runs pytest against the repository.
#
# You can adjust the behavior by modifying this file.
name: Run pytest

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version:
          - "3.7"  # EOL 2023-06-27
          - "3.8"  # EOL 2024-10
          - "3.9"  # EOL 2025-10
          - "3.10"  # EOL 2026-10
          - "3.11"  # EOL 2027-10
        experimental: [false]
        include:
          - python-version: 3.x
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - name: install poetry
        run: pipx install poetry
      - name: setup python-${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: poetry install
        run: poetry install
      - name: poetry run pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run pytest
          poetry run coveralls --service=github
