# This workflow runs scripts.
#
# You can adjust the behavior by modifying this file.
name: Run scripts with --help

on: [pull_request]

permissions:
  contents: read

jobs:
  scripts:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version:
          - "3.7"  # EOL 2023-06-27
          - "3.8"  # EOL 2024-10
          - "3.9"  # EOL 2025-10
          - "3.10"  # EOL 2026-10
          - "3.11"  # EOL 2027-10
        experimental: [false]
        include:
          - python-version: 3.x
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - name: install poetry
        run: pipx install poetry
      - name: setup python-${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: poetry install
        run: poetry install
      - name: initiliase --help
        run: poetry run -- zfs-replicate --help